name: Generate Video

on:
  repository_dispatch:
    types: [build_video]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QUOTE: "Whatever you want"
      AUTHOR: "Krishna"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        npm install

    - name: Install Chromium for Puppeteer
      run: npx puppeteer browsers install chrome

    - name: Set env from dispatch payload
      run: |
        echo "QUOTE=${{ github.event.client_payload.quote }}" >> $GITHUB_ENV
        echo "AUTHOR=${{ github.event.client_payload.author }}" >> $GITHUB_ENV

    - name: Render HTML to PNG
      run: npm run render

    - name: Convert PNG to MP4
      run: ffmpeg -loop 1 -i frame.png -c:v libx264 -t 10 -pix_fmt yuv420p output.mp4

    - name: Upload Video Artifact
      uses: actions/upload-artifact@v4
      with:
        name: video
        path: output.mp4
