name: Generate Video

on:
  repository_dispatch:
    types: [build_video]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QUOTE: "Whatever you want"   # default, will be overridden by payload
      AUTHOR: "Krishna"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node + Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        npm install puppeteer

    - name: Set env from dispatch payload
      run: |
        echo "QUOTE=${{ github.event.client_payload.quote }}" >> $GITHUB_ENV
        echo "AUTHOR=${{ github.event.client_payload.author }}" >> $GITHUB_ENV

    - name: Render HTML to PNG
      run: node render.js

    - name: Convert PNG to MP4
      run: ffmpeg -loop 1 -i frame.png -c:v libx264 -t 10 -pix_fmt yuv420p output.mp4

    - name: Upload Video Artifact
      uses: actions/upload-artifact@v3
      with:
        name: video
        path: output.mp4
